name: Check FTP Configuration

on:
  workflow_dispatch:

jobs:
  check-ftp:
    name: Verificar Configuração FTP
    runs-on: ubuntu-latest
    
    steps:
    - name: Check FTP Secrets Configuration
      run: |
        echo "🔐 Verificando configuração dos secrets FTP..."
        echo "============================================="
        echo ""
        
        # Verificar cada secret
        if [ -z "${{ secrets.FTP_SERVER }}" ]; then
          echo "❌ FTP_SERVER não configurado"
        else
          echo "✅ FTP_SERVER configurado: ${{ secrets.FTP_SERVER }}"
        fi
        
        if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
          echo "❌ FTP_USERNAME não configurado"
        else
          echo "✅ FTP_USERNAME configurado: ${{ secrets.FTP_USERNAME }}"
        fi
        
        if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "❌ FTP_PASSWORD não configurado"
        else
          echo "✅ FTP_PASSWORD configurado: [OCULTO]"
        fi
        
        if [ -z "${{ secrets.FTP_REMOTE_DIR }}" ]; then
          echo "⚠️ FTP_REMOTE_DIR não configurado (usará / como padrão)"
        else
          echo "✅ FTP_REMOTE_DIR configurado: ${{ secrets.FTP_REMOTE_DIR }}"
        fi
        
        if [ -z "${{ secrets.FTP_PORT }}" ]; then
          echo "ℹ️ FTP_PORT não configurado (usará 21 como padrão)"
        else
          echo "✅ FTP_PORT configurado: ${{ secrets.FTP_PORT }}"
        fi
        
        if [ -z "${{ secrets.SITE_URL }}" ]; then
          echo "ℹ️ SITE_URL não configurado (opcional para verificação)"
        else
          echo "✅ SITE_URL configurado: ${{ secrets.SITE_URL }}"
        fi
        
        echo ""
        echo "📋 Status geral:"
        
        # Verificar se os secrets obrigatórios estão configurados
        if [ -n "${{ secrets.FTP_SERVER }}" ] && [ -n "${{ secrets.FTP_USERNAME }}" ] && [ -n "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "🎉 Todos os secrets obrigatórios estão configurados!"
          echo "✅ Deploy automático está pronto para funcionar"
        else
          echo "⚠️ Secrets obrigatórios não configurados"
          echo ""
          echo "📝 Para configurar os secrets:"
          echo "1. Acesse: https://github.com/${{ github.repository }}/settings/secrets/actions"
          echo "2. Clique em 'New repository secret'"
          echo "3. Adicione os seguintes secrets:"
          echo "   - FTP_SERVER (obrigatório)"
          echo "   - FTP_USERNAME (obrigatório)"
          echo "   - FTP_PASSWORD (obrigatório)"
          echo "   - FTP_REMOTE_DIR (opcional, padrão: /)"
          echo "   - FTP_PORT (opcional, padrão: 21)"
          echo "   - SITE_URL (opcional, para verificação)"
        fi

    - name: Test FTP Connection (if configured)
      if: ${{ secrets.FTP_SERVER != '' && secrets.FTP_USERNAME != '' && secrets.FTP_PASSWORD != '' }}
      run: |
        echo "🔌 Testando conexão FTP..."
        
        # Instalar cliente FTP
        sudo apt-get update
        sudo apt-get install -y lftp
        
        # Testar conexão
        echo "Tentando conectar em: ${{ secrets.FTP_SERVER }}"
        
        lftp -c "
        set ftp:ssl-allow no;
        set ftp:passive-mode on;
        set net:timeout 10;
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
        pwd;
        quit
        " && echo "✅ Conexão FTP bem-sucedida!" || echo "❌ Falha na conexão FTP"