name: Deploy Portfolio to FTP

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'README.md'
      - 'DEPLOY.md' 
      - '.gitignore'
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
      
    - name: Validate basic file structure
      run: |
        echo "Checking file structure..."
        test -f index.htm && echo "✅ index.htm found" || (echo "❌ index.htm missing" && exit 1)
        test -f css/style.css && echo "✅ CSS found" || (echo "❌ CSS missing" && exit 1)
        test -f js/script.js && echo "✅ JS found" || (echo "❌ JS missing" && exit 1)
        echo "📊 File count: $(find . -type f \( -name "*.htm" -o -name "*.html" -o -name "*.css" -o -name "*.js" \) | wc -l) web files"
        
    - name: Test JSON files syntax
      run: |
        echo "Validating JSON files..."
        find . -name "*.json" -exec sh -c 'echo "Testing {}..." && python3 -m json.tool {} > /dev/null && echo "✅ {} valid"' \;
        
    - name: Check FTP secrets
      run: |
        echo "Checking required FTP secrets..."
        if [ -z "${{ secrets.FTP_SERVER }}" ]; then
          echo "❌ ERROR: FTP secrets are not configured!"
          echo "Please configure the following secrets in your GitHub repository:"
          echo "  - FTP_SERVER (your FTP server address)"
          echo "  - FTP_USERNAME (your FTP username)"
          echo "  - FTP_PASSWORD (your FTP password)"
          echo "  - FTP_REMOTE_DIR (target directory, e.g., /public_html)"
          echo "  - SITE_URL (your website URL for verification)"
          echo ""
          echo "Go to: Settings > Secrets and variables > Actions > New repository secret"
          exit 1
        fi
        echo "✅ FTP secrets are configured"
        echo "🌐 Target server: ${{ secrets.FTP_SERVER }}"
        echo "📁 Target directory: ${{ secrets.FTP_REMOTE_DIR }}"
        echo "🔗 Site URL: ${{ secrets.SITE_URL }}"
        
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/package*.json
          **/.github/**
          **/DEPLOY.md
          **/README.md
          **/validate.*
          **/*.log
          **/.env*
          
    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📅 Deployed at: $(date)"
        echo "🔗 Site should be live at: ${{ secrets.SITE_URL }}"
        echo "🚀 Check your website to confirm deployment"
